language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
#  - curl https://nhentai.net/language/chinese/
#  - curl https://nhentai.net/tag/full-color/
  - curl https://btsow.one/search/MNSE-019
  - curl https://btsow.one/search/ZEX-406
  - curl https://btsow.one/search/IPX-708
  - curl https://btsow.one/search/IPX-743
  - curl https://btsow.one/search/SHKD-955